version: '3'

services:
  web:
    build: frontend/.
    ports:
      - "8080:80"
    links:
      - api
  
  database:
    image: couchbase/server
      #volumes:
      #  - ~/couchbase/node1: /opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
  
  api:
    build: backend/.
    ports:
      - "8081:8080"
    links:
      - database
    depends_on: 
      - database

volumes:
  database-data:
