// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0-devel
// 	protoc        v3.12.0
// source: vetuser.proto

package vetuser

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type VetUserId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vid string `protobuf:"bytes,1,opt,name=vid,proto3" json:"vid,omitempty"`
}

func (x *VetUserId) Reset() {
	*x = VetUserId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vetuser_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VetUserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VetUserId) ProtoMessage() {}

func (x *VetUserId) ProtoReflect() protoreflect.Message {
	mi := &file_vetuser_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VetUserId.ProtoReflect.Descriptor instead.
func (*VetUserId) Descriptor() ([]byte, []int) {
	return file_vetuser_proto_rawDescGZIP(), []int{0}
}

func (x *VetUserId) GetVid() string {
	if x != nil {
		return x.Vid
	}
	return ""
}

type VetUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid        string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Vid        string `protobuf:"bytes,2,opt,name=vid,proto3" json:"vid,omitempty"`
	Gender     int32  `protobuf:"varint,3,opt,name=gender,proto3" json:"gender,omitempty"` // 0 = Divers - 1 = Male - 2 = Female
	FirstName  string `protobuf:"bytes,4,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName   string `protobuf:"bytes,5,opt,name=lastName,proto3" json:"lastName,omitempty"`
	IsEmployee bool   `protobuf:"varint,6,opt,name=isEmployee,proto3" json:"isEmployee,omitempty"`
	Dept       int32  `protobuf:"varint,7,opt,name=dept,proto3" json:"dept,omitempty"`
}

func (x *VetUser) Reset() {
	*x = VetUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vetuser_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VetUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VetUser) ProtoMessage() {}

func (x *VetUser) ProtoReflect() protoreflect.Message {
	mi := &file_vetuser_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VetUser.ProtoReflect.Descriptor instead.
func (*VetUser) Descriptor() ([]byte, []int) {
	return file_vetuser_proto_rawDescGZIP(), []int{1}
}

func (x *VetUser) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *VetUser) GetVid() string {
	if x != nil {
		return x.Vid
	}
	return ""
}

func (x *VetUser) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *VetUser) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *VetUser) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *VetUser) GetIsEmployee() bool {
	if x != nil {
		return x.IsEmployee
	}
	return false
}

func (x *VetUser) GetDept() int32 {
	if x != nil {
		return x.Dept
	}
	return 0
}

var File_vetuser_proto protoreflect.FileDescriptor

var file_vetuser_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x76, 0x65, 0x74, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x76, 0x65, 0x74, 0x75, 0x73, 0x65, 0x72, 0x22, 0x1d, 0x0a, 0x09, 0x56, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x76, 0x69, 0x64, 0x22, 0xb3, 0x01, 0x0a, 0x07, 0x56, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x76, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x45,
	0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69,
	0x73, 0x45, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x70,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x64, 0x65, 0x70, 0x74, 0x32, 0x43, 0x0a,
	0x0e, 0x56, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x31, 0x0a, 0x07, 0x67, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x2e, 0x76, 0x65, 0x74,
	0x75, 0x73, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x10,
	0x2e, 0x76, 0x65, 0x74, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x56, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_vetuser_proto_rawDescOnce sync.Once
	file_vetuser_proto_rawDescData = file_vetuser_proto_rawDesc
)

func file_vetuser_proto_rawDescGZIP() []byte {
	file_vetuser_proto_rawDescOnce.Do(func() {
		file_vetuser_proto_rawDescData = protoimpl.X.CompressGZIP(file_vetuser_proto_rawDescData)
	})
	return file_vetuser_proto_rawDescData
}

var file_vetuser_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vetuser_proto_goTypes = []interface{}{
	(*VetUserId)(nil), // 0: vetuser.VetUserId
	(*VetUser)(nil),   // 1: vetuser.VetUser
}
var file_vetuser_proto_depIdxs = []int32{
	0, // 0: vetuser.VetUserService.getUser:input_type -> vetuser.VetUserId
	1, // 1: vetuser.VetUserService.getUser:output_type -> vetuser.VetUser
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vetuser_proto_init() }
func file_vetuser_proto_init() {
	if File_vetuser_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vetuser_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VetUserId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vetuser_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VetUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vetuser_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vetuser_proto_goTypes,
		DependencyIndexes: file_vetuser_proto_depIdxs,
		MessageInfos:      file_vetuser_proto_msgTypes,
	}.Build()
	File_vetuser_proto = out.File
	file_vetuser_proto_rawDesc = nil
	file_vetuser_proto_goTypes = nil
	file_vetuser_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VetUserServiceClient is the client API for VetUserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VetUserServiceClient interface {
	GetUser(ctx context.Context, in *VetUserId, opts ...grpc.CallOption) (*VetUser, error)
}

type vetUserServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVetUserServiceClient(cc grpc.ClientConnInterface) VetUserServiceClient {
	return &vetUserServiceClient{cc}
}

func (c *vetUserServiceClient) GetUser(ctx context.Context, in *VetUserId, opts ...grpc.CallOption) (*VetUser, error) {
	out := new(VetUser)
	err := c.cc.Invoke(ctx, "/vetuser.VetUserService/getUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VetUserServiceServer is the server API for VetUserService service.
type VetUserServiceServer interface {
	GetUser(context.Context, *VetUserId) (*VetUser, error)
}

// UnimplementedVetUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVetUserServiceServer struct {
}

func (*UnimplementedVetUserServiceServer) GetUser(context.Context, *VetUserId) (*VetUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}

func RegisterVetUserServiceServer(s *grpc.Server, srv VetUserServiceServer) {
	s.RegisterService(&_VetUserService_serviceDesc, srv)
}

func _VetUserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VetUserId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VetUserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vetuser.VetUserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VetUserServiceServer).GetUser(ctx, req.(*VetUserId))
	}
	return interceptor(ctx, in, info, handler)
}

var _VetUserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "vetuser.VetUserService",
	HandlerType: (*VetUserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getUser",
			Handler:    _VetUserService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vetuser.proto",
}
